### ISSUE TITLE
填入API KEY后无法使用

### ISSUE THREAD

**Issue by FlyRocker** [Brain777777/bob-plugin-gemini#4]
https://generativelanguage.googleapis.com，这个URL404，填入Google的API保存后，翻译时提示“Unknown error”，请问这种情况应该怎么解决，网络环境是软路由科学

**Comment by Brain777777** [comment]
@FlyRocker 请求的模型被废弃了，稍等我这边更新下

**Comment by FlyRocker** [comment]
谢谢大佬
